#ifndef MIDI_ERRORS_H
#define MIDI_ERRORS_H

#include <stdint.h>

typedef enum _midi_error
{
    MIDI_ERROR_OK = 0,
    MIDI_ERROR_GENERAL = -1,
    MIDI_ERROR_INVALID_POINTER = -2,
    MIDI_ERROR_NOT_ENOUGH_DATA = -3,
    MIDI_ERROR_NOT_DATA = -4,
    MIDI_ERROR_NOT_NEW_MESSAGE = -5,
    MIDI_ERROR_STATUS_INVALID = -6,
    MIDI_ERROR_INVALID_MTHD_MARKER = -7,
    MIDI_ERROR_INVALID_MTHD_FORMAT = -8,
} midi_error_e;

#endif // MIDI_ERRORS_H
